### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by ulisigi** [Brentallica/prj-rev-bwfs-dasmoto#2]
Your page includes all of the styling provided by the design specification. Nice work!

Good use of alt attributes on your images, and the fallback font in your CSS. Small typo in the fallback font, though - it should be `sans-serif`.
https://github.com/Brentallica/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L2

**Comment by Brentallica** [comment]
Thank you so much!  I'm really happy.  :)
