### ISSUE TITLE
HTML Tags and Content

### ISSUE THREAD

**Issue by ulisigi** [Brentallica/prj-rev-bwfs-dasmoto#3]
Your HTML content matches the design specification, and your tags are used for their intended purpose.

As the projects grow in size and complexity, I recommend including more semantic elements in your HTML to help improve the readability, accessibility, and SEO (search engine optimization) of your code and page.

Here's a reference for semantic elements:
https://developer.mozilla.org/en/docs/Web/HTML/Element

Here's an article about semantic HTML and accessibility:
https://24ways.org/2017/accessibility-through-semantic-html/

**Comment by Brentallica** [comment]
Thank you so much!  I'm really happy.  :)
