### ISSUE TITLE
Rubric and Summary

### ISSUE THREAD

**Issue by ulisigi** [Brentallica/prj-rev-bwfs-dasmoto#4]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4/4
* _Comment(s):_ HTML file contains a valid link to the correct CSS file.
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ The page includes all styles and content provided in the design specification.
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4/4
* _Comment(s):_ Content: HTML content matches the design specification

Tags: The tags in the HTML are used for their intended purpose (<p> for paragraphs, <h_> for headers, etc.)
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4/4
* _Comment(s):_ Syntax: Uses proper selectors (id, class, element type). All rule sets are valid CSS.
 
### Overall Score: 16/16
Your project Exceeds Expectations - way to go! For extra practice of the concepts learned to this point, try building a personal web page. As you learn more from the course, you'll be able to update and improve your personal page for continued practice. By the end of the course, you'll have a great portfolio piece to showcase your new skills!
Overall, great job on your first project submitted for review. Keep up the excellent work, and happy coding!

**Comment by Brentallica** [comment]
Thank you so much!  I'm really happy.  :)
